/** @format */

import type { Metadata } from 'next';
import { Encode_Sans, Roboto } from 'next/font/google';
import './globals.css';

const encode = Encode_Sans({ subsets: ['latin'] });
const roboto = Roboto({ subsets: ['latin'], weight: ['500'] });

export const metadata: Metadata = {
	title: 'pokeApi app',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={encode.className}>{children}</body>
		</html>
	);
}
